/**
 * Project Configuration
 * Defines the curated portfolio order and public-safe metadata.
 */

export interface CustomProject {
  slug: string;
  name: string;
  description: string;
  html_url?: string;
  github_url?: string;
  demo_url?: string;
  website_url?: string;
  language: string;
  category: 'professional' | 'university' | 'personal';
  sourceType: 'open-source' | 'closed-source' | 'proprietary';
  priority: number;
  stargazers_count?: number;
  tags?: string[];
  role?: string;
  period?: string;
  impact?: string;
  status?: string;
  confidential?: boolean;
  group?: 'professional' | 'game-dev' | 'technical';
  thumbnail?: string;
  thumbnailFit?: 'cover' | 'contain';
  thumbnailBackground?: string;
  thumbnailPosition?: string;
  gallery_images?: string[];
  video_url?: string;
  hasInternalPage: boolean;
}

export type ProjectSource = CustomProject;

export const featuredProjects: CustomProject[] = [
  {
    slug: 'naiss-ride',
    name: 'naiss ride',
    description: 'Public-safe case study of mobile engineering inside a live startup app: rides, feed, camera, gamification, auth, payments, reliability, and release quality.',
    language: 'React Native',
    category: 'professional',
    sourceType: 'proprietary',
    priority: 1,
    role: 'Mobile Software Engineer',
    period: 'June 2026 - Present',
    impact: 'Live on iOS & Android at 4.6/5 on the App Store; built the rewards & ranking engine and a full camera-capture revamp, and shipped 40+ tickets on a near-weekly release cadence.',
    status: 'Active startup work',
    confidential: true,
    group: 'professional',
    tags: ['React Native', 'Expo', 'TypeScript', 'Convex', 'Sentry', 'PostHog', 'Jest', 'Detox'],
    thumbnail: '/assets/projects/naiss-ride-logo.png',
    thumbnailFit: 'contain',
    thumbnailBackground: '#03E888',
    hasInternalPage: true,
  },
  {
    slug: 'easeaccess24-automation',
    name: 'EaseAccess24 Automation',
    description: 'Internal AI and developer-productivity work: a Slack + Gemini intelligence system for meeting summaries and Jira sprint digests, a Shopify app, a VivaTech 2026 landing page, and an env-sync CLI.',
    language: 'Automation',
    category: 'professional',
    sourceType: 'proprietary',
    priority: 2,
    role: 'Software Engineering Intern',
    period: 'June 2026 - Present',
    impact: 'Shipped an internal Slack + Gemini intelligence system that turns meeting recordings into structured summaries and validated Jira sprint digests, plus a Shopify app, the VivaTech 2026 landing page, and a CLI that replaced manual .env sharing for a 12-person team.',
    status: 'Active internship',
    confidential: true,
    group: 'professional',
    tags: ['Next.js', 'Gemini', 'Docker', 'PostgreSQL', 'Shopify', 'CLI', 'AI Automation'],
    thumbnail: '/assets/projects/easeaccess24-logo.png',
    thumbnailFit: 'contain',
    hasInternalPage: true,
  },
  {
    slug: 'cleanr',
    name: 'Cleanr',
    description: 'Dual-sided apartment-cleaning marketplace built for users and cleaners across booking, matching, payments, maps, and mobile release execution.',
    website_url: 'https://www.getcleanr.io/',
    language: 'React Native',
    category: 'professional',
    sourceType: 'closed-source',
    priority: 3,
    role: 'Tech Lead & Full-Stack Developer',
    period: 'March 2025 - April 2026',
    impact: 'Led a 3-developer team across booking, matching, payments, maps, cancellation logic, and mobile release execution.',
    status: 'Past startup build',
    confidential: true,
    group: 'professional',
    tags: ['React Native', 'Expo', 'Firebase', 'Stripe', 'Google Maps'],
    thumbnail: '/assets/projects/cleanr pic.webp',
    video_url: 'https://youtu.be/81EEbJNf314',
    hasInternalPage: true,
  },
  {
    slug: 'streamscope',
    name: 'StreamScope',
    description: 'Real-time chat intelligence MVP for live streamers, built from zero in 10 days and awarded 2nd place at IE Tech Venture Bootcamp 2026.',
    language: 'Full Stack',
    category: 'university',
    sourceType: 'closed-source',
    priority: 4,
    role: 'Technical Lead',
    period: '2026',
    impact: 'Turned a messy creator-workflow problem into a focused MVP under a compressed deadline.',
    status: '2nd place',
    confidential: true,
    group: 'professional',
    tags: ['Real-Time', 'Chat Intelligence', 'MVP', 'Product Strategy'],
    thumbnail: '/assets/projects/streamscope-logo.jpg',
    thumbnailFit: 'contain',
    thumbnailBackground: '#040807',
    thumbnailPosition: 'center',
    gallery_images: [
      '/assets/projects/streamscope-analytics.jpg',
      '/assets/projects/streamscope-linkedin-demo.jpg',
      '/assets/projects/streamscope-linkedin-stage.jpg',
      '/assets/projects/streamscope-bootcamp.jpg'
    ],
    hasInternalPage: true,
  },
  {
    slug: 'iberdrola-datathon',
    name: 'Iberdrola Datathon',
    description: 'IE x Iberdrola datathon case study for Spain 2027 interurban EV charging rollout strategy, combining demand projection, grid readiness, corridor friction, and phased deployment planning.',
    language: 'Python',
    category: 'university',
    sourceType: 'proprietary',
    priority: 5,
    role: 'Data Strategy Contributor',
    period: '2026',
    impact: 'Converted messy infrastructure and demand data into a business-defensible rollout plan with reproducible outputs, maps, report assets, and pitch-ready evidence.',
    status: 'IE x Iberdrola datathon',
    confidential: true,
    group: 'technical',
    tags: ['Python', 'Jupyter', 'Data Strategy', 'EV Infrastructure', 'Maps'],
    thumbnail: '/assets/projects/iberdrola-datathon.png',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    gallery_images: [
      '/assets/projects/iberdrola-baseline-vs-proposal.png',
      '/assets/projects/iberdrola-friction-view.png'
    ],
    hasInternalPage: true,
  },
  {
    slug: 'aura-voice-assistant',
    name: 'AURA AI Receptionist',
    description: 'AI receptionist backend that turns Vapi voice tool-calls into onboarding email and calendar actions, with instant responses and background processing.',
    website_url: 'https://getaura.lu',
    language: 'Node.js',
    category: 'professional',
    sourceType: 'proprietary',
    priority: 6,
    role: 'Backend Automation Developer',
    period: '2026',
    impact: 'Live AI receptionist (getaura.lu) that secured 2 enterprise clients; handles voice-agent tool calls, webhook reliability, onboarding email, and calendar scheduling.',
    status: 'Private AI automation',
    confidential: true,
    group: 'professional',
    tags: ['Vapi.ai', 'Express', 'Postmark', 'Google Calendar', 'Webhooks'],
    thumbnail: '/assets/projects/aura-voice-assistant-cover.png',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    gallery_images: ['/assets/projects/aura-voice-assistant.svg'],
    hasInternalPage: true,
  },
  {
    slug: 'chess-anomaly-detection',
    name: 'Chess Anomaly Detection',
    description: 'Machine learning system for behavioral anomaly detection in online chess, comparing six unsupervised detectors and an ensemble review workflow.',
    github_url: 'https://github.com/Kiril-P/Final-Group-Project-Machine-Learning',
    language: 'Python',
    category: 'university',
    sourceType: 'open-source',
    priority: 7,
    role: 'ML Project Contributor',
    period: '2026',
    impact: 'LOF reached 0.971 test AUC on subtle synthetic injection; ensemble flagged 312 of 17,909 players for review.',
    status: '100/100 ML project',
    group: 'technical',
    tags: ['Machine Learning', 'Anomaly Detection', 'Lichess', 'Python'],
    thumbnail: '/assets/projects/chess-anomaly-detection.jpg',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    gallery_images: ['/assets/projects/chess pic2.webp'],
    hasInternalPage: true,
  },
  {
    slug: 'chess-engine',
    name: 'Chess Engine',
    description: 'Advanced chess engine implementing move validation, a GUI, turn switching, legal move highlighting, and bot play.',
    github_url: 'https://github.com/Kiril-P/ChessEngine',
    language: 'C++',
    category: 'university',
    sourceType: 'open-source',
    priority: 8,
    role: 'University Project Developer',
    period: '2025',
    impact: 'Built chess rules, GUI interaction, move highlighting, check/checkmate handling, and bot move logic.',
    status: 'Algorithms project',
    group: 'technical',
    tags: ['AI', 'Algorithms', 'C++'],
    thumbnail: '/assets/projects/chess pic1.webp',
    gallery_images: ['/assets/projects/chess pic2.webp'],
    video_url: 'https://youtu.be/g9J_QGgzTGg',
    hasInternalPage: true,
  },
  {
    slug: 'black-hole-render',
    name: 'Black Hole Render',
    description: 'Cinematic Three.js/WebGL black hole renderer with shader-driven lensing, bloom, adaptive quality, viewer controls, and PNG export.',
    github_url: 'https://github.com/Kiril-P/black-hole-render',
    language: 'Three.js',
    category: 'personal',
    sourceType: 'open-source',
    priority: 9,
    role: 'Solo Developer',
    period: '2026',
    impact: 'Shows WebGL fluency, shader-driven visual systems, performance awareness, and polish beyond ordinary CRUD projects.',
    status: 'Interactive WebGL render',
    group: 'technical',
    tags: ['Three.js', 'WebGL', 'Shaders', 'Vite', 'Visual Systems'],
    thumbnail: '/assets/projects/black-hole-render.png',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    hasInternalPage: true,
  },
  {
    slug: 'polygon-protocol',
    name: 'Polygon Protocol',
    description: 'Browser-playable geometric roguelite built in Godot for Mini Jam 202, centered on shape evolution, dash combat, bosses, and meta progression.',
    github_url: 'https://github.com/Kiril-P/Polygon-Protocol',
    demo_url: 'https://kirilp.itch.io/polygon-protocol',
    language: 'Godot',
    category: 'personal',
    sourceType: 'open-source',
    priority: 12,
    role: 'Solo Developer',
    period: '2026',
    impact: 'Released on itch.io with browser play and desktop downloads.',
    status: 'Mini Jam 202',
    group: 'game-dev',
    tags: ['Game Dev', 'Roguelite', 'Bullet Hell', 'GDScript'],
    thumbnail: '/assets/projects/polygonprotocol.webp',
    video_url: 'https://youtu.be/Yu9m_tLXc84',
    hasInternalPage: true,
  },
  {
    slug: 'starburst',
    name: 'StarBurst',
    description: 'Phaser bullet hell with multiple ships, bosses, power-ups, progression updates, and browser-first arcade pacing.',
    github_url: 'https://github.com/Kiril-P/starburst',
    demo_url: 'https://kirilp.itch.io/starburst',
    language: 'JavaScript',
    category: 'personal',
    sourceType: 'open-source',
    priority: 13,
    role: 'Solo Developer',
    period: '2025',
    impact: 'Submitted to Bullet Hell Jam 6 and iterated with devlogs and player feedback.',
    status: 'Bullet Hell Jam 6',
    group: 'game-dev',
    tags: ['Phaser', 'Bullet Hell', 'Canvas', 'Game Dev'],
    thumbnail: '/assets/projects/starburst1.webp',
    gallery_images: [
      '/assets/projects/starburst2.webp',
      '/assets/projects/starburst3.webp',
      '/assets/projects/starburst4.webp',
      '/assets/projects/starburst5.webp'
    ],
    hasInternalPage: true,
  },
  {
    slug: 'archmage-brolo-card-battle',
    name: 'Archmage Brolo: Card Battle',
    description: 'Static Slay the Spire-inspired wizard card battler focused on tactile card interactions, turn flow, targeting feedback, and polished browser play.',
    github_url: 'https://github.com/Kiril-P/slay-the-spire-esc-game',
    demo_url: 'https://slay-the-spire-esc-game.vercel.app',
    language: 'JavaScript',
    category: 'personal',
    sourceType: 'open-source',
    priority: 14,
    role: 'Solo Developer',
    period: '2026',
    impact: 'Demonstrates interaction polish, game-state architecture, animation timing, and static deployment discipline without a framework.',
    status: 'Playable prototype',
    group: 'game-dev',
    tags: ['Game Dev', 'Vanilla JS', 'Canvas', 'Card Battler', 'Vercel'],
    thumbnail: '/assets/projects/archmage-brolo-card-battle.png',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    hasInternalPage: true,
  },
  {
    slug: 'typing-wizard-duel',
    name: 'Typing Wizard Duel',
    description: 'Browser typing-combat prototype where exact multi-line spell input drives combat, combo, guard, enemy pressure, and duel events.',
    github_url: 'https://github.com/Kiril-P/typing-wizard-duel',
    demo_url: 'https://typing-wizard-duel.vercel.app',
    language: 'JavaScript',
    category: 'personal',
    sourceType: 'open-source',
    priority: 15,
    role: 'Solo Developer',
    period: '2026',
    impact: 'Turns a typing mechanic into a readable combat loop with separated managers for input, damage, enemy AI, events, UI, and animation.',
    status: 'Playable browser game',
    group: 'game-dev',
    tags: ['Game Dev', 'Typing', 'Vanilla JS', 'State Management'],
    thumbnail: '/assets/projects/typing-wizard-duel.png',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    hasInternalPage: true,
  },
  {
    slug: 'rush-hour-retail',
    name: 'Rush Hour Retail',
    description: '3D supermarket time-management game about shopping-list routing, cart tradeoffs, checkout timing, and high-pressure jam execution.',
    github_url: 'https://github.com/Kiril-P/Sim-Game',
    demo_url: 'https://kirilp.itch.io/rush-hour-retail',
    language: 'Godot',
    category: 'personal',
    sourceType: 'open-source',
    priority: 16,
    role: 'Solo Developer',
    period: '2026',
    impact: 'Adds a fast-shipped 3D game-jam project with real itch.io presentation and performance triage in an unfamiliar workflow.',
    status: 'Patch Notes v1.1',
    group: 'game-dev',
    tags: ['Godot', '3D Game', 'Game Jam', 'Itch.io'],
    thumbnail: '/assets/projects/rush-hour-retail.png',
    thumbnailFit: 'cover',
    thumbnailPosition: 'center',
    hasInternalPage: true,
  },
  {
    slug: 'nomnomnow',
    name: 'NomNomNow',
    description: 'Serverless food delivery backend architecture using AWS Lambda, DynamoDB, API Gateway, Cognito, and real-time order workflow patterns.',
    github_url: 'https://github.com/Kiril-P/Cloud-Computing-Final-Project',
    demo_url: 'https://kpetrovski.me/Cloud-Computing-Final-Project/',
    language: 'TypeScript',
    category: 'university',
    sourceType: 'open-source',
    priority: 10,
    role: 'Cloud Architecture Developer',
    period: '2025',
    impact: 'Designed a complete cloud-backed ordering system with serverless deployment and API architecture.',
    status: 'University project',
    group: 'technical',
    tags: ['AWS', 'TypeScript', 'Serverless', 'APIs'],
    thumbnail: '/assets/projects/nomnomnow pic.webp',
    video_url: 'https://youtu.be/CGYAp0squuc',
    hasInternalPage: true,
  },
  {
    slug: 'battleship',
    name: 'Battleship Multiplayer',
    description: 'Networked multiplayer Battleship in C with POSIX sockets, custom binary protocol, threading, and terminal UI.',
    github_url: 'https://github.com/Kiril-P/Battleship-Multiplayer-Game',
    language: 'C',
    category: 'university',
    sourceType: 'open-source',
    priority: 11,
    role: 'Systems Programmer',
    period: '2025',
    impact: 'Built a LAN-playable client-server game with concurrent connection handling.',
    status: 'Systems project',
    group: 'technical',
    tags: ['Networking', 'C', 'Sockets', 'Threads'],
    thumbnail: '/assets/projects/Battleship.webp',
    gallery_images: [
      '/assets/projects/Battleship (1).webp',
      '/assets/projects/Battleship (2).webp',
      '/assets/projects/Battleship (3).webp',
      '/assets/projects/Battleship (4).webp'
    ],
    hasInternalPage: true,
  },
  {
    slug: 'solitaire',
    name: 'Solitaire',
    description: 'Classic card game implementation with drag-and-drop mechanics and win-state detection.',
    language: 'Java',
    category: 'university',
    sourceType: 'open-source',
    priority: 17,
    role: 'University Project Developer',
    period: '2025',
    impact: 'Implemented card movement, rules, and GUI interaction for a complete playable solitaire project.',
    status: 'Java GUI project',
    group: 'game-dev',
    tags: ['Java', 'GUI', 'Logic'],
    thumbnail: '/assets/projects/solitaire.webp',
    gallery_images: [
      '/assets/projects/solitaire2.webp',
      '/assets/projects/solitaire3.webp'
    ],
    hasInternalPage: true,
  }
];

export const shouldUseFeaturedProjects = featuredProjects.length > 0;
